site_name: juku3000
site_description: The eternal digital life of the school computer JUKU
site_url: https://j3k.borjch.com/
repo_name: infoaed/juku3000
repo_url: https://github.com/infoaed/juku3000
edit_uri: ""
site_author: juku3000
extra_css:
   - css/extra.css

exclude_docs: |
  Mikroarvuti Juku E5101 kasutamisjuhend 1988 (168lk, eesti k).pdf
  JUKU E5104 Kasutusjuhend 3 osa (286lk, vene k).pdf

theme:
    name: material
    logo: images/juku3000_small.svg
    favicon: images/favicon.svg
    language: en
    custom_dir: docs/overrides
    palette:
      - media: "(prefers-color-scheme)"
        primary: deep-purple
        toggle:
          icon: material/brightness-auto    
          name: "Automatic brightness"
      - scheme: 'default'
        primary: deep-purple
        media: '(prefers-color-scheme: light)'
        toggle:
          icon: 'material/lightbulb'
          name: "Text on a dark background"
      - scheme: 'slate'
        primary: deep-purple
        media: '(prefers-color-scheme: dark)'
        toggle:
          icon: 'material/lightbulb-outline'
          name: 'Text on a light background'
    features:
        - navigation.sections
        - header.autohide
        - content.code.copy
        - content.footnote.tooltips        

markdown_extensions:
    - admonition
    - codehilite
    - footnotes
    - attr_list
    - md_in_html
    - pymdownx.blocks.caption
    - pymdownx.magiclink
    - toc:
        permalink: true

plugins:
  - social:

nav:
    - Hello, Juhan!: index.md
    - JUKU life cycle: ajajoon.md
    - Using EKDOS: juku-käsud.md
    - Running MAME: mame-käivitamine.md
    - Recording videos: videod.md
    - Reading disks: kettad.md
    - Games disc 2024: mängude-ketas-2024.md
    - Games disc 2025: porditud-mängud-2025.md
    - Software catalog: tarkvara-kataloog.md
    - '👾 Try JUKU in your browser! 👾': 'https://infoaed.ee/juku'
